name: Update Sound Generator

on:
  schedule:
    - cron: "0 0 * * *" # Every day at midnight UTC
  workflow_dispatch:

jobs:
  update_sounds:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyttsx3 soundfile numpy

      - name: Install ffmpeg
        run: sudo apt-get update && sudo apt-get install -y ffmpeg

      - name: Download Ollama (binary only, no systemd)
        run: |
          curl -L https://github.com/ollama/ollama/releases/latest/download/ollama-linux-amd64 -o ollama
          chmod +x ollama
          sudo mv ollama /usr/local/bin/

      - name: Pull Deepseek R1 model
        run: ollama pull deepseek-r1

      - name: Start Ollama server
        run: |
          nohup ollama serve > ollama.log 2>&1 &
          sleep 20
          curl -s http://localhost:11434/api/version || (echo "Ollama did not start!" && cat ollama.log && exit 1)

      - name: Generate Deepseek R1 prompt
        run: |
          sed "s|<insert generator.py contents here>|$(cat generator.py)|" deepseek_prompt.txt > prompt_final.txt

      - name: Call Deepseek R1 to update code
        run: |
          RESPONSE=$(curl -s -X POST http://localhost:11434/api/chat \
            -H "Content-Type: application/json" \
            -d '{
              "model": "deepseek-r1",
              "messages": [
                {"role": "system", "content": "You are an expert Python developer."},
                {"role": "user", "content": '"$(jq -Rs . < prompt_final.txt)"'}
              ]
            }')
          echo "$RESPONSE" | jq -r '.message.content' > generator.py

      - name: Run updated Python script to generate sounds
        run: python generator.py

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add generator.py sounds/
          git commit -m "Auto-update sounds and code via Deepseek R1" || echo "No changes to commit"
          git push

      - name: Print Ollama logs (always)
        if: always()
        run: cat ollama.log || echo "No Ollama logs found"
