name: Update Sound Generator

on:
  schedule:
    - cron: "0 0 * * *" # Every day at midnight UTC
  workflow_dispatch:

jobs:
  update_sounds:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyttsx3 soundfile numpy

      - name: Install ffmpeg
        run: sudo apt-get update && sudo apt-get install -y ffmpeg

      - name: Generate Gemini prompt file
        run: |
          cp gemini_prompt.txt prompt_final.txt
          echo "" >> prompt_final.txt
          cat generator.py >> prompt_final.txt

      - name: Call Gemini 2.0 Flash to update code
        env:
          GEMINI_API_TOKEN: ${{ secrets.GEMINI_API_TOKEN }}
        run: |
          RESPONSE=$(curl -s -X POST "https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent?key=$GEMINI_API_TOKEN" \
            -H "Content-Type: application/json" \
            -d '{
              "contents": [
                {"role": "user", "parts": [{"text": "'"$(cat prompt_final.txt)"'"}]}
              ]
            }')
          echo "$RESPONSE" | jq -r '.candidates[0].content.parts[0].text' > generator.py

      - name: Run updated Python script to generate sounds
        run: python generator.py

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add generator.py sounds/
          git commit -m "Auto-update sounds and code via Gemini 2.0 Flash" || echo "No changes to commit"
          git push